import car_1 from '../assets/images/cars/1.jpeg';
import car_2 from '../assets/images/cars/2.jpeg';

export default {
  carsReducer: {
    cars: [
      {
        id: 1,
        model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 2,
        model: 'Nissan Sunny',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 3,
        model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 4,
        model: 'Nissan Sunny',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_2,
      },
      {
        id: 5,
        model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 6,
        model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 7,
        model: 'Nissan Sunny',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_2,
      },
      {
        id: 8,
        model: 'Nissan Sunny',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_2,
      },
      {
        id: 9,
        model: 'Kia Rio',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '15',
        doors: '4',
        luggages: '3',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_1,
      },
      {
        id: 10,
        model: 'Nissan Sunny',
        color: 'White',
        bodyStyle: 'Sedan',
        pricePerDay: '20',
        doors: '4',
        luggages: '2',
        seats: '5',
        engine: 'V',
        emissionsClass: 'Euro 6',
        transmission: 'Automatic',
        rentDeposit: '300',
        carImg: car_2,
      },
    ],
  },
};
